-- Paw Star Database Schema
-- MySQL / MariaDB Compatible

CREATE DATABASE IF NOT EXISTS DB_PST DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE DB_PST;

-- 1. 사용자 테이블 (plamodelshop 회원관리 구조와 동일/호환)
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID VARCHAR(100) PRIMARY KEY,
    NICKNAME VARCHAR(50) NOT NULL,
    PROFILE_IMG VARCHAR(255) DEFAULT '/static/image/profile/default_profile.png',
    BIO VARCHAR(255) DEFAULT '반려동물 집사입니다 🐾',
    ROLE VARCHAR(20) DEFAULT 'USER', -- USER, ADMIN
    LAST_LOGIN_AT DATETIME DEFAULT CURRENT_TIMESTAMP, -- 최근 로그인 일시
    LOGIN_COUNT INT DEFAULT 0,                        -- 로그인 횟수
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 2. 콘테스트 회차 테이블
CREATE TABLE IF NOT EXISTS CONTEST (
    CONTEST_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,              -- 예: 제1회 Paw Star 콘테스트
    DESCRIPTION TEXT,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'SCHEDULED',    -- SCHEDULED(예정), IN_PROGRESS(진행중), CLOSED(종료)
    BANNER_IMG VARCHAR(255),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 3. 배지 테이블
CREATE TABLE IF NOT EXISTS BADGE (
    BADGE_ID INT AUTO_INCREMENT PRIMARY KEY,
    BADGE_NAME VARCHAR(50) NOT NULL,
    BADGE_ICON VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255)
);

-- 4. 게시물 테이블 (반려동물 사진/영상 자랑)
CREATE TABLE IF NOT EXISTS POST (
    POST_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL,
    CONTEST_ID INT NOT NULL,
    PET_NAME VARCHAR(50) NOT NULL,             -- 반려동물 이름
    PET_TYPE VARCHAR(30) DEFAULT 'DOG',        -- DOG, CAT, BIRD, OTHER 등
    TITLE VARCHAR(150) NOT NULL,
    CONTENT TEXT,
    FILE_PATH VARCHAR(255) NOT NULL,
    LIST_FILE_NAME VARCHAR(150) NOT NULL,
    POPUP_FILE_NAME VARCHAR(150) NOT NULL,
    MEDIA_TYPE VARCHAR(10) DEFAULT 'IMAGE',    -- IMAGE, VIDEO
    SCORE INT DEFAULT 0,                       -- 실시간 합산 점수
    VIEW_COUNT INT DEFAULT 0,                  -- 조회 수 (+1)
    LIKE_COUNT INT DEFAULT 0,                  -- 좋아요 수 (+5)
    COMMENT_COUNT INT DEFAULT 0,               -- 댓글 수 (+10)
    SHARE_COUNT INT DEFAULT 0,                 -- 공유 수
    RANKING INT DEFAULT NULL,                  -- 대회 전체/당선 순위
    BADGE_ID INT DEFAULT NULL,                 -- 당선 배지 ID
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (CONTEST_ID) REFERENCES CONTEST(CONTEST_ID) ON DELETE CASCADE,
    FOREIGN KEY (BADGE_ID) REFERENCES BADGE(BADGE_ID) ON DELETE SET NULL
);

-- 5. 콘테스트 수상자 테이블
CREATE TABLE IF NOT EXISTS CONTEST_WINNER (
    WINNER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CONTEST_ID INT NOT NULL,
    POST_ID INT NOT NULL,
    USER_ID VARCHAR(100) NOT NULL,
    AWARD_TYPE VARCHAR(30) NOT NULL, -- SUPER_STAR(1위), RISING_STAR(2위), BRIGHT_STAR(3위), ROOKIE_STAR(급상승 1위)
    PRIZE_NAME VARCHAR(100) DEFAULT '상품권 및 명예 칭호', -- 확장성: 상품권 이벤트
    AWARDED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CONTEST_ID) REFERENCES CONTEST(CONTEST_ID) ON DELETE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 6. 사용자 배지 테이블
CREATE TABLE IF NOT EXISTS USER_BADGE (
    USER_ID VARCHAR(100) NOT NULL,
    CONTEST_ID INT NOT NULL,
    BADGE_ID INT NOT NULL,
    GRANTED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, CONTEST_ID, BADGE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (CONTEST_ID) REFERENCES CONTEST(CONTEST_ID) ON DELETE CASCADE,
    FOREIGN KEY (BADGE_ID) REFERENCES BADGE(BADGE_ID) ON DELETE CASCADE
);

-- 7. 공통 코드 테이블 [PST_CD]
CREATE TABLE IF NOT EXISTS PST_CD (
    CD VARCHAR(20) PRIMARY KEY,
    GRP VARCHAR(20) NOT NULL,
    CD_NM VARCHAR(100) NOT NULL
);

INSERT INTO PST_CD (CD, GRP, CD_NM) VALUES
('G001C001', 'G001', '진행중'),
('G001C002', 'G001', '종료'),
('G002P001', 'G002', '전체'),
('G002P002', 'G002', '품종')
ON DUPLICATE KEY UPDATE GRP=VALUES(GRP), CD_NM=VALUES(CD_NM);
